/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function H3xKey(props) {
  const { nodes, materials } = useGLTF('/assets/models/h3xK3y.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[1.001, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials['GOLD meterial']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_3.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_4.geometry}
          material={materials['Rough white metal']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_5.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_6.geometry}
          material={materials['GOLD meterial.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_7.geometry}
          material={materials['GOLD meterial.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_8.geometry}
          material={materials['GOLD meterial.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_9.geometry}
          material={materials['GOLD meterial.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_10.geometry}
          material={materials['GOLD meterial.006']}
        />
      </group>
    </group>
  )
}

export default H3xKey;

useGLTF.preload('/assets/models/h3xK3y.glb')