import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import BG from '@/components/BG'

import { useRef, useState, Suspense } from 'react'
import * as THREE from 'three'
import { Canvas } from '@react-three/fiber'
import { useHelper, OrbitControls, PivotControls } from '@react-three/drei'
import { H3xkey } from '@/public/H3xkey'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>h3x | club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Aldrich&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Libre+Barcode+39+Text&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
        <BG/>
        <div className={styles.detailsContainer}>
          <h1 className={styles.hexcollectionTitle}>h<span className={styles.h3x}>3</span>x K<span className={styles.h3x}>3</span>y</h1>
          <div className={styles.hexkeyContainer}>
            <div className={styles.hexkey}>
              <Canvas>
                <ambientLight intensity={1}/>
                <directionalLight intensity={13} position={(10, 0, 10)} color="#fcf8ea" />
                <directionalLight intensity={30} position={(10, 20, -10)} color="#fcf8ea"/>
                <directionalLight intensity={30} position={(0, 10, -10)} color="#fcf8ea"/>
                <OrbitControls autoRotate enableDamping enablePan={false} enableZoom={false} enableRotate/>
                  <Suspense fallback={null}>
                    <H3xkey/>
                  </Suspense>
              </Canvas>
            </div>
            <div className={styles.hexkeyDetails}>
              <p>
                Your key to the h3xav3rse. Unlocks your unique player profile along with a unique smart wallet able to collect and hold h3x tok3ns, h3xArt3facts, and NFTs from h3xColl3ction.
              </p>
              <iframe
                src="https://embed.ipfscdn.io/ipfs/bafybeicd3qfzelz4su7ng6n523virdsgobrc5pcbarhwqv3dj3drh645pi/?contract=0x8D7D3401280757047eD70C659579A9eaE6FF8B04&chain=%7B%22name%22%3A%22Polygon+Mainnet%22%2C%22chain%22%3A%22Polygon%22%2C%22rpc%22%3A%5B%22https%3A%2F%2F137.rpc.thirdweb.com%2F%24%7BTHIRDWEB_API_KEY%7D%22%5D%2C%22nativeCurrency%22%3A%7B%22name%22%3A%22MATIC%22%2C%22symbol%22%3A%22MATIC%22%2C%22decimals%22%3A18%7D%2C%22shortName%22%3A%22matic%22%2C%22chainId%22%3A137%2C%22testnet%22%3Afalse%2C%22slug%22%3A%22polygon%22%2C%22icon%22%3A%7B%22url%22%3A%22ipfs%3A%2F%2FQmcxZHpyJa8T4i63xqjPYrZ6tKrt55tZJpbXcjSDKuKaf9%2Fpolygon%2F512.png%22%2C%22width%22%3A512%2C%22height%22%3A512%2C%22format%22%3A%22png%22%7D%7D&clientId=b12826c2df78232047f7ff112ef10e9e&theme=dark&primaryColor=yellow"
                width="600px"
                height="600px"
                frameborder="0"
              ></iframe>
            </div>
          </div>
        </div>
        <div className={styles.hexcollectionContainer}>
            <h1 className={styles.hexcollectionTitle}>h<span className={styles.h3x}>3</span>x Coll<span className={styles.h3x}>3</span>ction</h1>
            <h2 className={styles.hexCollectionName}>G<span className={styles.h3x}>3</span>n<span className={styles.h3x}>3</span>sis</h2>
            <Image className={styles.hexCollection} src='/stars.jpg' height="1920" width='1080'/>
            <a href="https://opensea.io/collection/h3x-g3n3sis" target="_blank">
              <button type="button" className={styles.hexCollectionButton}>Explore</button>
            </a>
          </div>

          <div className={styles.hexstationContainer}>
            <h1 className={styles.hexstationTitle}>h<span className={styles.h3x}>3</span>xav<span className={styles.h3x}>3</span>rse</h1>
            <Image className={styles.hexstation} src='/hexstation.png' height="1920" width='1080'/>
            <p className={styles.imageText}>Coming Soon...</p>
          </div>
        </div>
      </main>
    </>
  )
}
